import "./globals.css";
import ApplicationsProvider from "../components/ApplicationsProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ApplicationsProvider>{children}</ApplicationsProvider>
      </body>
    </html>
  );
}
